name: first workflow
on: [ workflow_dispatch ]
jobs: 
    shell-runner: 
        runs-on: ubuntu-latest 
        steps:
            - run: | 
                echo "hello world"
                echo "I am learning github actions and now i am serious"

    second-job: 
        runs-on: ubuntu-latest
        needs: shell-runner
        steps: 
            - run: echo "this is the second job"