name: Manually Triggered
on: 
    workflow_dispatch: 
jobs: 
    shell-commands: 
        runs-on: ubuntu-latest
        steps: 
            - run: echo "this is running after manually clicked"
            - name: printing the ref name
              run: echo $GITHUB_REF
    