name: Manually Triggered
on: 
    workflow_dispatch:
    push: 
        branches: 
            - main 
jobs: 
    shell-commands: 
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps: 
            - run: echo "this is running after manually clicked"
    
    