name: parallel checks
on: [ workflow_dispatch ]  # by using this you can run this workflow manually 
jobs: 
    shell-runner: 
        runs-on: ubuntu-latest
        steps: 
            - run: | 
                echo "$(whoami)"
    
    macos-job: 
        runs-on: macos-latest
        needs: shell-runner
        steps: 
            - run: echo $(whoami)
    
    windows-job: 
        runs-on: windows-latests
        needs: shell-runner 
        steps: 
            - run: echo "hello from windows"
    