name: workflow Commands 
on: [push]
jobs: 
    running-wf-commands: 
        runs-on: ubuntu-latest
        steps: 
            # to return a error in your workflow 
            - run: echo "::error file=app.js line1::Missing semicolon"